curl
-H "Content-Type: application/json"
-X POST
-d '{"name":"Dang Le Gia vu","email":"vudang@lazada.elogistic.com"}'
http://localhost:3000/api/v1/student

curl -H "Content-Type: application/json" -X POST -d '{"name":"Dang Le Gia vu","email":"vudang@lazada.elogistic.com","dob":"2000-02-22"}' http://localhost:8080/api/v1/student